spring:
  application:
    name: Herobrine
  jpa:
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      initialize-schema: always
logging:
  level:
    root: info
    de.kaleidox: debug
    org.comroid: debug
    com.ampznetwork: debug
